---
name: portcullis
version: 0.1.0.0
github: "git@github.com:jzwood/portcullis.git"
license: BSD3
author: "Jake Wood"
maintainer: ""
copyright: "2021 Jake Wood"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: A minimal programming language

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6.5.1
  - hspec == 2.7.10
  - QuickCheck == 2.14.2

library:
  source-dirs: src

executables:
  portcullis-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - portcullis

tests:
  portcullis-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - portcullis
  doctests:
    source-dirs: doctests
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - doctest
